workflows:
  react-native-workflow:
    name: Build iOS with Expo
    environment:
      node: 18
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          npm ci
      - name: Prebuild
        script: |
          npx expo install
          npx expo prebuild
      - name: Build iOS app
        script: |
         npx expo build:ios --non-interactive
    artifacts:
      - ios/build/**/*.ipa
