workflows:
  expo-eas-ios:
    name: EAS Build for iOS
    environment:
      vars:
        CI: true
      node: 18
      xcode: latest
    scripts:
      - name: Install EAS CLI and dependencies
        script: |
          npm install -g eas-cli
          npm install
      - name: Configure EAS
        script: |
          eas build:configure --non-interactive || true
      - name: Run EAS iOS Build
        script: |
          eas build --platform ios --non-interactive --profile preview
    artifacts:
      - build/**/*.ipa
